package dh.meli.spring_elastic.model;

import lombok.Getter;
import lombok.Setter;

/* AUTOR NÃO SERÁ UM DOCUMENTO, AUTOR É PARTE DE UM DOCUMENTO, POR ISSO ELE NÃO TERÁ UM IDENTIFICADOR EXCLUSIVO
* O ELASTIC PERMITE BUSCAR POR QUALQUER CAMPO
* MAS O ÍNDICE PRIMÁRIO DELE É O ID DO ARTIGO
* NESTE EXEMPLO NÃO TEM CONTROLE NENHUM COM RELAÇÃO AO CAMPO ID. OU SEJA, PODERÃO HAVER REPETIÇÕES */

@Getter @Setter
public class Author {
    // QUANDO NÃO TEMOS ANOTAÇÕES EXPLICITAS PARA DIZER O QUE SERÃO ESSES CAMPOS, ELES SERÃO CRIADOS DE FORMA AUTOMÁTICA COM BASE NO TIPO DO ATRIBUTO E O QUE SERÁ RECEBIDO PELO JSON.
    private int id;
    private String name;
}
